---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: louis-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://acia-cfia-gpu-staging-dns-eay3uqut.hcp.canadacentral.azmk8s.io:443
    namespace: louis
  source:
    repoURL: https://github.com/ai-cfia/howard.git
    path: kubernetes/aks/apps/louis/base/ui
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: louis-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://acia-cfia-gpu-staging-dns-eay3uqut.hcp.canadacentral.azmk8s.io:443
    namespace: louis
  source:
    repoURL: https://github.com/ai-cfia/howard.git
    path: kubernetes/aks/apps/louis/base/backend
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
