apiVersion: v1
kind: Secret
metadata:
  name: kratos-secret
  namespace: ori
  labels:
    app.kubernetes.io/name: kratos
    app.kubernetes.io/instance: ori-kratos
    app.kubernetes.io/version: "v1.0.0"
    argocd.argoproj.io/instance: ori
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: kratos-0.39.1
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "0"
    helm.sh/resource-policy: keep
type: Opaque
data:
  dsn: "example-dsn-base64-encoded"
  secretsDefault: "random-generated-secret-base64-encoded"
  secretsCookie: "random-generated-secret-base64-encoded"
  secretsCipher: "random-generated-secret-base64-encoded"
  smtpConnectionURI: "example-smtp-connection-uri-base64-encoded"
