apiVersion: v1
kind: Secret
metadata:
  name: test-app-secrets
  annotations:
    avp.kubernetes.io/path: "kv/data/devsecops_admin_keys"
    avp.kubernetes.io/secret-version: "13"
stringData:
  MINIO_SECRET_KEY: <rootPassword>
  MINIO_ACCESS_KEY: <rootUser>
type: Opaque
