apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: inspection-alpha-canada-ca
spec:
  secretName: apex-domain-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: inspection.alpha.canada.ca
  dnsNames:
  - inspection.alpha.canada.ca
