apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus
data:
  config.yaml: |
    metrics: true
    ui:
      title: "Health Dashboard | AI-Lab | CFIA"
      header: "AI-Lab Web Hosted Apps"
      logo: "https://raw.githubusercontent.com/ai-cfia/finesse-frontend/main/src/assets/CFIA_Banner.png"
    storage:
      type: sqlite
      path: /data/data.db
    alerting:
      discord:
        webhook-url: $DISCORD_WEBHOOK_URL
    endpoints:
      - name: "AI-Lab website"
        url: https://ailab.inspection.alpha.canada.ca/
        interval: 2m
        conditions:
          - "[STATUS] == 200"
          - "len([BODY]) > 0"
          - "[BODY] == pat(*<html>*)"
        alerts:
          - type: discord
            description: "AI-Lab website healthcheck failed"
            send-on-resolved: true
            failure-threshold: 1

      - name: "Fertiscan website"
        url: https://fertiscan.inspection.alpha.canada.ca/
        interval: 2m
        conditions:
          - "[STATUS] == 200"
          - "len([BODY]) > 0"
          - "[BODY] == pat(*<html>*)"
        alerts:
          - type: discord
            description: "Fertiscan website healthcheck failed"
            send-on-resolved: true
            failure-threshold: 1

      - name: "Nachet website"
        url: https://nachet.inspection.alpha.canada.ca/
        interval: 2m
        conditions:
          - "[STATUS] == 200"
          - "len([BODY]) > 0"
          - "[BODY] == pat(*<html>*)"
        alerts:
          - type: discord
            description: "Nachet website healthcheck failed"
            send-on-resolved: true
            failure-threshold: 1

      - name: "Finesse website"
        url: https://finesse.inspection.alpha.canada.ca/
        interval: 2m
        conditions:
          - "[STATUS] == 200"
          - "len([BODY]) > 0"
          - "[BODY] == pat(*<html>*)"
        alerts:
          - type: discord
            description: "Finesse website healthcheck failed"
            send-on-resolved: true
            failure-threshold: 1

      - name: "Finesse internal website"
        url: https://finesse-internal.inspection.alpha.canada.ca/
        interval: 2m
        conditions:
          - "[STATUS] == 200"
          - "len([BODY]) > 0"
          - "[BODY] == pat(*<html>*)"
        alerts:
          - type: discord
            description: "Finesse internal website healthcheck failed"
            send-on-resolved: true
            failure-threshold: 1

      - name: "Louis website"
        url: https://louis.inspection.alpha.canada.ca/
        interval: 2m
        conditions:
          - "[STATUS] == 200"
          - "len([BODY]) > 0"
          - "[BODY] == pat(*<html>*)"
        alerts:
          - type: discord
            description: "Louis website healthcheck failed"
            send-on-resolved: true
            failure-threshold: 1

      - name: "Librechat website"
        url: https://librechat.inspection.alpha.canada.ca/
        interval: 2m
        conditions:
          - "[STATUS] == 200"
          - "len([BODY]) > 0"
          - "[BODY] == pat(*<html>*)"
        alerts:
          - type: discord
            description: "Librechat website healthcheck failed"
            send-on-resolved: true
            failure-threshold: 1

      - name: "ArgoCD website"
        url: https://argocd.inspection.alpha.canada.ca/
        interval: 2m
        conditions:
          - "[STATUS] == 200"
          - "len([BODY]) > 0"
          - "[BODY] == pat(*<html>*)"
        alerts:
          - type: discord
            description: "Argocd website healthcheck failed"
            send-on-resolved: true
            failure-threshold: 1

      - name: "Grafana website"
        url: https://grafana.inspection.alpha.canada.ca/
        interval: 2m
        conditions:
          - "[STATUS] == 200"
          - "len([BODY]) > 0"
          - "[BODY] == pat(*<html>*)"
        alerts:
          - type: discord
            description: "Grafana website healthcheck failed"
            send-on-resolved: true
            failure-threshold: 1

      - name: "Bytebase website"
        url: https://bytebase.inspection.alpha.canada.ca/
        interval: 2m
        conditions:
          - "[STATUS] == 200"
          - "len([BODY]) > 0"
          - "[BODY] == pat(*<html>*)"
        alerts:
          - type: discord
            description: "Bytebase website healthcheck failed"
            send-on-resolved: true
            failure-threshold: 1

      - name: "Vouch endpoint"
        url: https://vouch.inspection.alpha.canada.ca/healthcheck
        interval: 2m
        conditions:
          - "[STATUS] == 200"
          - "len([BODY]) > 0"
        alerts:
          - type: discord
            description: "Vouch website healthcheck failed"
            send-on-resolved: true
            failure-threshold: 1

      - name: "Vault website"
        url: https://vault.inspection.alpha.canada.ca/
        interval: 2m
        conditions:
          - "[STATUS] == 200"
          - "len([BODY]) > 0"
          - "[BODY] == pat(*<html>*)"
        alerts:
          - type: discord
            description: "Vault website healthcheck failed"
            send-on-resolved: true
            failure-threshold: 1

      - name: "test-app website"
        url: https://test-app.inspection.alpha.canada.ca/ok
        interval: 2m
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: discord
            description: "test-app website healthcheck failed"
            send-on-resolved: true
            failure-threshold: 1
