apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: gatus
  name: gatus
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
