---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbeaver
  namespace: cloudbeaver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudbeaver
  template:
    metadata:
      labels:
        app: cloudbeaver
    spec:
      containers:
        - name: cloudbeaver
          image: dbeaver/cloudbeaver:24.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8978
          livenessProbe:
            httpGet:
              path: /
              port: 8978
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8978
            initialDelaySeconds: 40
            periodSeconds: 10
          volumeMounts:
            - name: dbeaver-product
              mountPath: /opt/cloudbeaver/conf/product.conf
              subPath: product.conf
            - name: dbeaver-sources-user
              mountPath: /opt/cloudbeaver/workspace/user-projects/admin.dbeaver/.dbeaver/data-sources.json
              subPath: data-sources.json
            - name: dbeaver-sources-global
              mountPath: /opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json
              subPath: data-sources.json
            - name: dbeaver-server
              mountPath: /opt/cloudbeaver/conf/cloudbeaver.conf
              subPath: cloudbeaver.conf
            - name: dbeaver-initial-data
              mountPath: /opt/cloudbeaver/conf/initial-data.conf
              subPath: initial-data.conf
      volumes:
        - name: dbeaver-product
          configMap:
            name: dbeaver-product-configmap-76t74t24mh
        - name: dbeaver-sources-user
          configMap:
            name: dbeaver-sources-user-configmap-t8m94c4gb7
        - name: dbeaver-sources-global
          configMap:
            name: dbeaver-sources-global-configmap-t8m94c4gb7
        - name: dbeaver-server
          configMap:
            name: dbeaver-server-configmap-9tgdffkdbb
        - name: dbeaver-initial-data
          configMap:
            name: dbeaver-initial-data-configmap-t58fgmffkg

---
apiVersion: v1
kind: Service
metadata:
  name: cloudbeaver
  namespace: cloudbeaver
spec:
  clusterIP: None
  selector:
    app: cloudbeaver
  ports:
    - protocol: TCP
      port: 8978
