apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 1000
      #   runAsGroup: 3000
      #   fsGroup: 2000
      #   allowPrivilegeEscalation: false
      #   readOnlyRootFilesystem: true
      #   capabilities:
      #     drop:
      #       - ALL
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - open-webui
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - agent
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          # resources:
          #   requests:
          #     cpu: "2000m"
          #     memory: "4Gi"
          #   limits:
          #     cpu: "2000m"
          #     memory: "6Gi"
          env:
            - name: OLLAMA_BASE_URL
              value: "http://10.0.51.223:11434"
          tty: true
          volumeMounts:
            - name: webui-volume
              mountPath: /app/backend/data
      volumes:
        - name: webui-volume
          persistentVolumeClaim:
            claimName: open-webui-pvc

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: open-webui-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: open-webui
