- op: replace
  path: /spec/template/spec/volumes/2
  value:
    name: cacerts
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "istio-tls"
