---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-telemetry-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  sources:
    - chart: opentelemetry-operator
      helm:
        releaseName: opentelemetry-operator
        valueFiles:
          - $values/kubernetes/aks/system/monitoring/helm/otel-operator-values.yaml
      repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      targetRevision: 0.69.0
    - repoURL: https://github.com/ai-cfia/howard.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
