---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  sources:
    - chart: grafana
      helm:
        releaseName: grafana
        valueFiles:
          - $values/kubernetes/aks/system/monitoring/helm/grafana-values.yaml
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 7.3.3
    - repoURL: https://github.com/ai-cfia/howard.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
