---
extends: default

rules:
  line-length:
    max: 1000 # Some Helm charts have fixed values that cannot be modified without altering the chart itself.
    allow-non-breakable-inline-mappings: true
