schedules:
- cron: "0 15 * * 1-5"
  displayName: Stop Cluster on Weekdays at 5 PM
  branches:
    include:
    - main
  always: true

- cron: "30 15 * * 1-5"
  displayName: Start Cluster on Weekdays at 7 AM
  branches:
    include:
    - main
  always: true

trigger:
  branches:
    include:
    - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: cron-toggle-power-k8s-cluster

stages:
- stage: ManageCluster
  jobs:
  - job: ManageAKSCluster
    steps:
    - task: AzureCLI@2
      displayName: "Login to Azure"
      inputs:
        azureSubscription: $(serviceConnectionName)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Successfully logged in to Azure"

    - task: AzureCLI@2
      displayName: "Manage AKS Cluster"
      inputs:
        azureSubscription: $(serviceConnectionName)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          # Conditional operation based on the time trigger
          if [[ "$(Build.SourceBranch)" == "cron:0 15 * * 1-5" ]]; then
            az aks stop --name $(aksName) --resource-group $(resourceGroupName)
            az aks show --name $(aksName) --resource-group $(resourceGroupName)
          elif [[ "$(Build.SourceBranch)" == "cron:30 15 * * 1-5" ]]; then
            az aks start --name $(aksName) --resource-group $(resourceGroupName)
            az aks show --name $(aksName) --resource-group $(resourceGroupName)
