schedules:
- cron: "0 17 * * 1-5"
  displayName: Stop Cluster on Weekdays at 3 PM
  branches:
    include:
    - main
  always: true

- cron: "0 7 * * 1-5"
  displayName: Start Cluster on Weekdays at 3:30 PM
  branches:
    include:
    - main
  always: true

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: cron-toggle-power-k8s-cluster

stages:
- stage: ManageCluster
  jobs:
  - job: ManageAKSCluster
    steps:
    - task: AzureCLI@2
      displayName: "Login to Azure"
      inputs:
        azureSubscription: $(serviceConnectionName)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Successfully logged in to Azure"

    - task: AzureCLI@2
      displayName: "Manage AKS Cluster"
      inputs:
        azureSubscription: $(serviceConnectionName)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          # Conditional operation based on the time trigger
          if [ "$(Build.CronSchedule.DisplayName)" == "Stop Cluster on Weekdays at 3 PM" ]; then
            echo "Stopping AKS cluster based on schedule..."
            az aks stop --name $(aksName) --resource-group $(resourceGroupName)
            az aks show --name $(aksName) --resource-group $(resourceGroupName)
          elif [ "$(Build.CronSchedule.DisplayName)" == "Start Cluster on Weekdays at 3:30 PM" ]; then
            echo "Starting AKS cluster based on schedule..."
            az aks start --name $(aksName) --resource-group $(resourceGroupName)
            az aks show --name $(aksName) --resource-group $(resourceGroupName)
