---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  sources:
    - chart: argo-cd
      helm:
        releaseName: argocd
        valueFiles:
          - $values/kubernetes/aks/system/argocd/helm/values.yaml
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 6.7.3
    - repoURL: https://github.com/ai-cfia/howard.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ai-cfia/howard.git
      path: kubernetes/aks/system/argocd/base
      targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
