---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  sources:
    - chart: ingress-nginx
      helm:
        releaseName: ingress-nginx
        valueFiles:
          - $values/kubernetes/aks/system/ingress-nginx/helm/values.yaml
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.10.0
    - repoURL: https://github.com/ai-cfia/howard.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-gpu-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ingress-nginx
    server: https://acia-cfia-gpu-staging-dns-eay3uqut.hcp.canadacentral.azmk8s.io:443
  sources:
    - chart: ingress-nginx
      helm:
        releaseName: ingress-nginx
        valueFiles:
          - $values/kubernetes/aks/system/ingress-nginx/helm/values.gpu.yaml
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.10.0
    - repoURL: https://github.com/ai-cfia/howard.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
