apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: bytebase-pgsql
  namespace: bytebase
spec:
  instances: 1
  superuserSecret:
    name: superuser-secret

  bootstrap:
    initdb:
      database: bytebase-pgsql
      owner: cfia-admin
      secret:
        name: bytebase-pgsql-secret
  storage:
    size: 20Gi
