apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oneuptime
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: oneuptime
    server: https://kubernetes.default.svc
  sources:
    - chart: oneuptime
      helm:
        releaseName: oneuptime
        valueFiles:
          - $values/kubernetes/aks/system/oneuptime/helm/values.yaml
      repoURL: https://helm-chart.oneuptime.com
      targetRevision: 7.0.1989
    - repoURL: https://github.com/ai-cfia/howard.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ai-cfia/howard.git
      path: kubernetes/aks/system/oneuptime/base
      targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
