apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oneuptime
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: oneuptime
    server: https://kubernetes.default.svc
  sources:
    - chart: oneuptime
      repoURL: https://helm-chart.oneuptime.com
      targetRevision: 7.0.2936
      plugin:
        env:
          - name: HELM_VALUES
            value: |
              global:
                storageClass: managed-csi
                clusterDomain: &global-cluster-domain cluster.local
                host: oneuptime.inspection.alpha.canada.ca
                httpProtocol: https
                oneuptimeSecret: ""
                encryptionSecret: ""
                openTelemetryCollectorHost: ""
                fluentdHost: ""
              deployment:
                replicaCount: 1
              metalLb:
                enabled: false
                ipAdddressPool:
                  enabled: false
                  addresses: []
              ingress:
                service:
                  type: ClusterIP
                  externalIPs: []
              postgresql:
                image:
                  tag: 15-debian-11
                clusterDomain: *global-cluster-domain
                auth:
                  username: postgres
                  database: oneuptimedb
                  password: "<path:kv/data/oneuptime/postgresql#password>"
                architecture: standalone
                primary:
                  service:
                    ports:
                      postgresql: "5432"
                  terminationGracePeriodSeconds: 0
                  persistence:
                    size: 25Gi
                readReplicas:
                  terminationGracePeriodSeconds: 0
                  persistence:
                    size: 25Gi
              clickhouse:
                clusterDomain: *global-cluster-domain
                service:
                  ports:
                    http: "8123"
                shards: 1
                replicaCount: 1
                terminationGracePeriodSeconds: 0
                zookeeper:
                  enabled: false
                persistence:
                  size: 25Gi
                auth:
                  username: oneuptime
                  password: "<path:kv/data/oneuptime/clickhouse#password>"
                initdbScripts:
                  db-init.sql: |
                    CREATE DATABASE oneuptime;
              redis:
                clusterDomain: *global-cluster-domain
                architecture: standalone
                auth:
                  enabled: true
                master:
                  persistence:
                    enabled: false
                replica:
                  persistence:
                    enabled: false
                commonConfiguration: |-
                  appendonly no
                  save ""
              image:
                registry: ghcr.io
                repository: oneuptime
                pullPolicy: Always
                tag: 7.0.2936
                restartPolicy: Always
              autoscaling:
                enabled: false
                minReplicas: 1
                maxReplicas: 100
                targetCPUUtilizationPercentage: 80
                targetMemoryUtilizationPercentage: 80
              nodeEnvironment: production
              billing:
                enabled: false
                publicKey: ""
                privateKey: ""
                smsDefaultValueInCents: ""
                callDefaultValueInCentsPerMinute: ""
                smsHighRiskValueInCents: ""
                callHighRiskValueInCentsPerMinute: ""
              subscriptionPlan:
                basic: ""
                growth: ""
                scale: ""
                enterprise: ""
              analytics:
                host: ""
                key: ""
              internalSmtp:
                sendingDomain: ""
                dkimPrivateKey: ""
                dkimPublicKey: ""
                email: ""
                name: ""
              incidents:
                disableAutomaticCreation: false
              probes:
                one:
                  name: "Probe"
                  description: "Probe"
                  monitoringWorkers: 3
                  monitorFetchLimit: 10
                  key: ""
                  replicaCount: 1
              port:
                app: 3002
                ingestor: 3400
                testServer: 3800
                accounts: 3003
                statusPage: 3105
                dashboard: 3009
                adminDashboard: 3158
                nginx: 80
                haraka: 2525
                probe: 3500
                otelCollectorGrpc: 4317
                otelCollectorHttp: 4318
                isolatedVM: 4572
              testServer:
                enabled: false
              openTelemetryExporter:
                endpoint: "http://alloy.monitoring.svc.cluster.local:4317"
              containerSecurityContext: {}
              podSecurityContext: {}
              logLevel: DEBUG
              oneuptimeIngress:
                enabled: true
                annotations:
                  nginx.ingress.kubernetes.io/whitelist-source-range: 10.5.0.0/16,205.194.32.0/24,51.159.99.250,62.210.173.51,51.159.101.36,172.174.206.132,57.151.99.117
                  external-dns.alpha.kubernetes.io/target: inspection.alpha.canada.ca
                  cert-manager.io/cluster-issuer: letsencrypt-prod
                  kubernetes.io/tls-acme: "true"
                className: nginx
                hosts:
                  - oneuptime.inspection.alpha.canada.ca
                tls:
                  enabled: true
                  hosts:
                    - oneuptime.inspection.alpha.canada.ca
                      secretName: status-https-cert
    - repoURL: https://github.com/ai-cfia/howard.git
      path: kubernetes/aks/system/oneuptime/base
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
