---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # User applications
  - ../finesse/
  - ../nachet/
  - ../bytebase/
  - ../louis/
  - ../librechat/
  - ../ailab/
  - ../fertiscan/
  - ../webtop/
  - ../landing/

  # System applications
  - ../../system/cert-manager/
  - ../../system/vault/
  - ../../system/argocd/
  - ../../system/external-dns/
  - ../../system/ingress-nginx/
  - ../../system/monitoring/
  - ../../system/cloudnativepg/
  - ../../system/vouch-proxy/
  - ../../system/trivy/
  # - ../../system/oneuptime/
  # - ../../system/oneuptime/custom-probe/
  - ../../system/falco/
  # - ../../system/istio/
  - ../../system/gatus/

patches:
  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: not-used
        finalizers:
          - resources-finalizer.argocd.argoproj.io
      spec:
        syncPolicy:
          automated:
            selfHeal: true
    target:
      kind: Application
