apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  annotations:
    avp.kubernetes.io/path: "kv/data/github-runner"
    avp.kubernetes.io/secret-version: "2"
data:
  github_app_id: "<github_app_id>"
  github_app_installation_id: "<github_app_installation_id>"
  github_app_private_key: <github_app_private_key>
  github_webhook_secret_token: <github_webhook_secret_token>
type: Opaque
