---
kratos:
  config:
    dsn: postgres://kratos:your_password@ori-postgresql-service:5432/kratos
    secrets:
      default:
        - dolore occaecat nostrud Ut
    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: file:///etc/config/identity.default.schema.json
    courier:
      smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
    selfservice:
      default_browser_return_url: https://oathkeeper.inspection.alpha.canada.ca/
  automigration:
    enabled: true
  deployment:
    environmentSecretsName: kratos-secrets
  ingress:
    admin:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/target: inspection.alpha.canada.ca
        cert-manager.io/cluster-issuer: letsencrypt-prod
        ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: kratos-admin.inspection.alpha.canada.ca
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - kratos-admin.inspection.alpha.canada.ca
          secretName: aciacfia-tls
    public:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/target: inspection.alpha.canada.ca
        cert-manager.io/cluster-issuer: letsencrypt-prod
        ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: kratos.inspection.alpha.canada.ca
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - kratos.inspection.alpha.canada.ca
          secretName: aciacfia-tls
  statefulset:
    extraEnv:
      - name: DSN
        valueFrom:
          secretKeyRef:
            name: kratos-secrets
            key: dsn
      - name: SECRETS_DEFAULT
        valueFrom:
          secretKeyRef:
            name: kratos-secrets
            key: secretsDefault
  identitySchemas:
    "identity.default.schema.json": |
      {
        "$id": "https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "Person",
        "type": "object",
        "properties": {
          "traits": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email",
                "title": "E-Mail",
                "ory.sh/kratos": {
                  "credentials": {
                    "password": {
                      "identifier": true
                    }
                  },
                  "recovery": {
                    "via": "email"
                  },
                  "verification": {
                    "via": "email"
                  }
                }
              }
            },
            "required": [
              "email"
            ],
            "additionalProperties": false
          }
        }
      }
