apiVersion: apps/v1
kind: Deployment
metadata:
  name: fertiscan-backend
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: fertiscan-backend
  template:
    metadata:
      labels:
        app: fertiscan-backend
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - fertiscan-backend
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - agent
      containers:
        - name: fertiscan-backend
          image: ghcr.io/ai-cfia/fertiscan-backend:169-as-a-devops-i-want-to-enable-the-team-with-better-observability-over-the-product-performance
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: fertiscan-backend-secrets
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://alloy.monitoring.svc.cluster.local:4318"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: logs
              mountPath: /app/logs
            - name: uploads
              mountPath: /app/uploads
            - name: tmp
              mountPath: /cachedir_joblib
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: tmp
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: uploads
          emptyDir: {}
          # resources:
          #   requests:
          #     cpu: "250m"
          #     memory: "512Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "1Gi"


---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fertiscan-backend-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: fertiscan-backend

---
apiVersion: v1
kind: Service
metadata:
  name: fertiscan-backend-svc
spec:
  clusterIP: None
  selector:
    app: fertiscan-backend
  ports:
    - protocol: TCP
      port: 5000
