apiVersion: apps/v1
kind: Deployment
metadata:
  name: fertiscan-backend
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: fertiscan-backend
  template:
    metadata:
      labels:
        app: fertiscan-backend
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - fertiscan-backend
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - agent
      containers:
        - name: fertiscan-backend
          image: ghcr.io/ai-cfia/fertiscan-backend:98-add-user-and-group-to-dockerfile
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: fertiscan-backend-secrets
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: tmp
              mountPath: /cachedir_joblib
            - name: app-volume
              mountPath: /app
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: tmp
          emptyDir: {}
        - name: app-volume
          emptyDir: {}
          # resources:
          #   requests:
          #     cpu: "250m"
          #     memory: "512Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "1Gi"


---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fertiscan-backend-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: fertiscan-backend

---
apiVersion: v1
kind: Service
metadata:
  name: fertiscan-backend-svc
spec:
  clusterIP: None
  selector:
    app: fertiscan-backend
  ports:
    - protocol: TCP
      port: 5000
