kind: Secret
apiVersion: v1
metadata:
  name: fertiscan-pgsql-app-user
  annotations:
    avp.kubernetes.io/path: "kv/data/fertiscan/database"
    avp.kubernetes.io/secret-version: "1"
type: kubernetes.io/basic-auth
stringData:
  password: <APP_USER_PASSWORD>
  username: <APP_USER_USERNAME>

---
kind: Secret
apiVersion: v1
metadata:
  name: fertiscan-pgsql-superuser
  annotations:
    avp.kubernetes.io/path: "kv/data/fertiscan/database"
    avp.kubernetes.io/secret-version: "1"
type: kubernetes.io/basic-auth
stringData:
  password: <SUPERUSER_PASSWORD>
  username: <SUPERUSER_USERNAME>
