kind: Secret
apiVersion: v1
metadata:
  name: fertiscan-backend-secrets
  annotations:
    avp.kubernetes.io/path: "kv/data/fertiscan/backend"
    avp.kubernetes.io/secret-version: "21"
stringData:
  AZURE_API_ENDPOINT: <AZURE_API_ENDPOINT>
  AZURE_API_KEY: <AZURE_API_KEY>
  AZURE_OPENAI_ENDPOINT: <AZURE_OPENAI_ENDPOINT>
  AZURE_OPENAI_KEY: <AZURE_OPENAI_KEY>
  AZURE_OPENAI_DEPLOYMENT: <AZURE_OPENAI_DEPLOYMENT>
  FERTISCAN_STORAGE_URL: <FERTISCAN_STORAGE_URL>
  PROMPT_PATH: <PROMPT_PATH>
  UPLOAD_PATH: <UPLOAD_PATH>
  FRONTEND_URL: <FRONTEND_URL>
  FERTISCAN_DB_URL: <FERTISCAN_DB_URL>
  FERTISCAN_SCHEMA: <FERTISCAN_SCHEMA>
  API_BASE_PATH: <API_BASE_PATH>
  SWAGGER_BASE_PATH: <SWAGGER_BASE_PATH>
  SWAGGER_PATH: <SWAGGER_PATH>


---
kind: Secret
apiVersion: v1
metadata:
  name: fertiscan-frontend-secrets
  annotations:
    avp.kubernetes.io/path: "kv/data/fertiscan/frontend"
    avp.kubernetes.io/secret-version: "3"
stringData:
  REACT_APP_ACTIVATE_USING_JSON: <REACT_APP_ACTIVATE_USING_JSON>
  API_URL: <API_URL>
  REACT_APP_STATE_OBJECT_SIZE_LIMIT: <REACT_APP_STATE_OBJECT_SIZE_LIMIT>
