---
kind: Secret
apiVersion: v1
metadata:
  name: nachet-secrets
  annotations:
    avp.kubernetes.io/path: "kv/data/nachet"
    avp.kubernetes.io/secret-version: "2"
stringData:
  NACHET_AZURE_STORAGE_CONNECTION_STRING: <NACHET_AZURE_STORAGE_CONNECTION_STRING>
  NACHET_DATA: <NACHET_DATA>
  NACHET_RESOURCE_GROUP: <NACHET_RESOURCE_GROUP>
  NACHET_SUBSCRIPTION_ID: <NACHET_SUBSCRIPTION_ID>
  NACHET_WORKSPACE: <NACHET_WORKSPACE>
  NACHET_MODEL: <NACHET_MODEL>
  NACHET_BLOB_PIPELINE_NAME: <NACHET_BLOB_PIPELINE_NAME>
  NACHET_BLOB_PIPELINE_VERSION: <NACHET_BLOB_PIPELINE_VERSION>
  NACHET_BLOB_PIPELINE_DECRYPTION_KEY: <NACHET_BLOB_PIPELINE_DECRYPTION_KEY>
