apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nachet-backend-spc
  namespace: nachet
spec:
  provider: azure
  secretObjects:
    - secretName: nachet-backend-secrets
      type: Opaque
      labels:
        app: nachet-backend
      data:
        - objectName: nachet-azure-storage-connection-string
          key: NACHET_AZURE_STORAGE_CONNECTION_STRING
        - objectName: nachet-data
          key: NACHET_DATA
        - objectName: nachet-blob-account
          key: NACHET_BLOB_ACCOUNT
        - objectName: nachet-blob-key
          key: NACHET_BLOB_KEY
        - objectName: nachet-blob-pipeline-name
          key: NACHET_BLOB_PIPELINE_NAME
        - objectName: nachet-blob-pipeline-version
          key: NACHET_BLOB_PIPELINE_VERSION
        - objectName: nachet-blob-pipeline-decryption-key
          key: NACHET_BLOB_PIPELINE_DECRYPTION_KEY
        - objectName: nachet-db-url
          key: NACHET_DB_URL
        - objectName: nachet-max-content-length
          key: NACHET_MAX_CONTENT_LENGTH
        - objectName: nachet-schema
          key: NACHET_SCHEMA
        - objectName: nachet-storage-url
          key: NACHET_STORAGE_URL
        - objectName: nachet-valid-dimension
          key: NACHET_VALID_DIMENSION
        - objectName: nachet-valid-extension
          key: NACHET_VALID_EXTENSION
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: fa9cd720-ddc4-4dc8-9be6-5d0fc8c4a3fb # to be updated with identity from dev cluster. current one is from staging azurekeyvaultsecretprovider-acia-cfia-staging-cluster
    keyvaultName: ailab-key-vault-dev
    cloudName: ""
    objects: |
      array:
        - |
          objectName: nachet-azure-storage-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: nachet-data
          objectType: secret
          objectVersion: ""
        - |
          objectName: nachet-blob-account
          objectType: secret
          objectVersion: ""
        - |
          objectName: nachet-blob-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: nachet-blob-pipeline-name
          objectType: secret
          objectVersion: ""
        - |
          objectName: nachet-blob-pipeline-version
          objectType: secret
          objectVersion: ""
        - |
          objectName: nachet-blob-pipeline-decryption-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: nachet-db-url
          objectType: secret
          objectVersion: ""
        - |
          objectName: nachet-max-content-length
          objectType: secret
          objectVersion: ""
        - |
          objectName: nachet-schema
          objectType: secret
          objectVersion: ""
        - |
          objectName: nachet-storage-url
          objectType: secret
          objectVersion: ""
        - |
          objectName: nachet-valid-dimension
          objectType: secret
          objectVersion: ""
        - |
          objectName: nachet-valid-extension
          objectType: secret
          objectVersion: ""
    tenantId: 18b5a5ed-1d86-41d3-94a0-bc27dae32ab2
