---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nachet-backend
  namespace: nachet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nachet-backend
  template:
    metadata:
      labels:
        app: nachet-backend
    spec:
      containers:
        - name: nachet-backend
          image: ghcr.io/ai-cfia/nachet-backend:51-implementing-2-models
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: [hypercorn -b :8080 app:app]
          envFrom:
            - secretRef:
                name: nachet-secrets
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: nachet-backend-svc
  namespace: nachet
spec:
  clusterIP: None
  selector:
    app: nachet-backend
  ports:
    - protocol: TCP
      port: 8080
