kind: Secret
apiVersion: v1
metadata:
  name: nachet-backend-secrets
  annotations:
    avp.kubernetes.io/path: "kv/data/nachet"
    avp.kubernetes.io/secret-version: "2"
stringData:
  NACHET_AZURE_STORAGE_CONNECTION_STRING: <NACHET_AZURE_STORAGE_CONNECTION_STRING>
  NACHET_DATA: <NACHET_DATA>
  NACHET_RESOURCE_GROUP: <NACHET_RESOURCE_GROUP>
  NACHET_SUBSCRIPTION_ID: <NACHET_SUBSCRIPTION_ID>
  NACHET_WORKSPACE: <NACHET_WORKSPACE>
  NACHET_MODEL: <NACHET_MODEL>
  NACHET_BLOB_PIPELINE_NAME: <NACHET_BLOB_PIPELINE_NAME>
  NACHET_BLOB_PIPELINE_VERSION: <NACHET_BLOB_PIPELINE_VERSION>
  NACHET_BLOB_PIPELINE_DECRYPTION_KEY: <NACHET_BLOB_PIPELINE_DECRYPTION_KEY>
---
kind: Secret
apiVersion: v1
metadata:
  name: nachet-frontend-secrets
  annotations:
    avp.kubernetes.io/path: "kv/data/nachet"
    avp.kubernetes.io/secret-version: "4"
stringData:
  PUBLIC_URL: <NACHET_FRONTEND_PUBLIC_URL>
  VITE_BACKEND_URL: <NACHET_FRONTEND_VITE_BACKEND_URL>
  VITE_APP_MODE: <NACHET_FRONTEND_VITE_APP_MODE>
