kind: Secret
apiVersion: v1
metadata:
  name: nachet-backend-config
  annotations:
    avp.kubernetes.io/path: "kv/data/nachet/dev/config"
    avp.kubernetes.io/secret-version: "3"
stringData:
  NACHET_SCHEMA: <NACHET_SCHEMA>
  NACHET_DATA: <NACHET_DATA>
  NACHET_MAX_CONTENT_LENGTH: <NACHET_MAX_CONTENT_LENGTH>
  NACHET_BLOB_PIPELINE_NAME: <NACHET_BLOB_PIPELINE_NAME>
  NACHET_BLOB_PIPELINE_VERSION: <NACHET_BLOB_PIPELINE_VERSION>
  NACHET_VALID_DIMENSION: <NACHET_VALID_DIMENSION>
  NACHET_VALID_EXTENSION: <NACHET_VALID_EXTENSION>
  NACHET_FRONTEND_URL: <NACHET_FRONTEND_URL>
  NACHET_CONNECTION_PROTOCOL: <NACHET_CONNECTION_PROTOCOL>
  NACHET_STORAGE_SUFFIX: <NACHET_STORAGE_SUFFIX>
---
kind: Secret
apiVersion: v1
metadata:
  name: nachet-backend-secrets
  annotations:
    avp.kubernetes.io/path: "kv/data/nachet/dev/secrets"
    avp.kubernetes.io/secret-version: "3"
stringData:
  NACHET_BLOB_ACCOUNT: <NACHET_BLOB_ACCOUNT>
  NACHET_BLOB_KEY: <NACHET_BLOB_KEY>
  NACHET_BLOB_PIPELINE_DECRYPTION_KEY: <NACHET_BLOB_PIPELINE_DECRYPTION_KEY>
  NACHET_BLOB_URL: <NACHET_BLOB_URL>
  NACHET_DB_USER: <NACHET_DB_USER>
  NACHET_DB_PASSWORD: <NACHET_DB_PASSWORD>
  NACHET_DB_URL: <NACHET_DB_URL>
  NACHET_ENV: <NACHET_ENV>
---
kind: Secret
apiVersion: v1
metadata:
  name: nachet-frontend-secrets
  annotations:
    avp.kubernetes.io/path: "kv/data/nachet"
    avp.kubernetes.io/secret-version: "13"
stringData:
  PUBLIC_URL: <NACHET_FRONTEND_URL>
  VITE_BACKEND_URL: <NACHET_FRONTEND_VITE_BACKEND_URL>
  VITE_APP_MODE: <NACHET_FRONTEND_VITE_APP_MODE>
---
kind: Secret
apiVersion: v1
metadata:
  name: nachet-rcnn-detector-secrets
  annotations:
    avp.kubernetes.io/path: "kv/data/nachet"
    avp.kubernetes.io/secret-version: "13"
stringData:
  NACHET_ENV: <NACHET_ENV>
  NACHET_BACKEND_SVC_URL: <NACHET_BACKEND_SVC_URL>
---
kind: Secret
apiVersion: v1
metadata:
  name: nachet-swin-classifier-secrets
  annotations:
    avp.kubernetes.io/path: "kv/data/nachet"
    avp.kubernetes.io/secret-version: "13"
stringData:
  NACHET_ENV: <NACHET_ENV>
  NACHET_BACKEND_SVC_URL: <NACHET_BACKEND_SVC_URL>
