apiVersion: apps/v1
kind: Deployment
metadata:
  name: nachet-rcnn-detector
  namespace: nachet
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nachet-rcnn-detector
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nachet-rcnn-detector
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 1000
        runAsGroup: 1000
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nachet-rcnn-detector
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - agent
      containers:
        - name: nachet-rcnn-detector
          image: ghcr.io/ai-cfia/nachet-backend:29-azureml-seed-detector
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ['cp -r /project/* /app/ && azmlinfsrv --entry_script /artifacts/scoring_file_v_1_0_0.py']
          envFrom:
            - secretRef:
                name: nachet-rcnn-detector-secrets
          ports:
            - containerPort: 5001
          volumeMounts:
            - name: logs
              mountPath: /app/logs
            - name: tmp
              mountPath: /app
          livenessProbe:
            httpGet:
              path: /score
              port: 5001
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests:
              cpu: "250m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "2Gi"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: tmp
          persistentVolumeClaim:
            claimName: nachet-tmp-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: nachet-logs-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nachet-logs-pvc
spec:
  storageClassName: azurefile
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nachet-tmp-pvc
spec:
  storageClassName: azurefile
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nachet-rcnn-detector-pdb
  namespace: nachet
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: nachet-rcnn-detector

---
apiVersion: v1
kind: Service
metadata:
  name: nachet-rcnn-detector-svc
  namespace: nachet
spec:
  clusterIP: None
  selector:
    app: nachet-rcnn-detector
  ports:
    - protocol: TCP
      port: 5001
