kind: Secret
apiVersion: v1
metadata:
  name: nachet-backend-secrets
  annotations:
    avp.kubernetes.io/path: "kv/data/nachet"
    avp.kubernetes.io/secret-version: "5"
stringData:
  NACHET_AZURE_STORAGE_CONNECTION_STRING: <NACHET_AZURE_STORAGE_CONNECTION_STRING>
  NACHET_DATA: <NACHET_DATA>
  NACHET_BLOB_ACCOUNT: <NACHET_BLOB_ACCOUNT>
  NACHET_BLOB_KEY: <NACHET_BLOB_KEY>
  NACHET_BLOB_PIPELINE_NAME: <NACHET_BLOB_PIPELINE_NAME>
  NACHET_BLOB_PIPELINE_VERSION: <NACHET_BLOB_PIPELINE_VERSION>
  NACHET_BLOB_PIPELINE_DECRYPTION_KEY: <NACHET_BLOB_PIPELINE_DECRYPTION_KEY>
  NACHET_DB_URL: <NACHET_DB_URL>
  NACHET_MAX_CONTENT_LENGTH: <NACHET_MAX_CONTENT_LENGTH>
  NACHET_SCHEMA: <NACHET_SCHEMA>
  NACHET_STORAGE_URL: <NACHET_STORAGE_URL>
  NACHET_VALID_DIMENSION: <NACHET_VALID_DIMENSION>
  NACHET_VALID_EXTENSION: <NACHET_VALID_EXTENSION>
---
kind: Secret
apiVersion: v1
metadata:
  name: nachet-frontend-secrets
  annotations:
    avp.kubernetes.io/path: "kv/data/nachet"
    avp.kubernetes.io/secret-version: "3"
stringData:
  PUBLIC_URL: <NACHET_FRONTEND_PUBLIC_URL>
  VITE_BACKEND_URL: <NACHET_FRONTEND_VITE_BACKEND_URL>
  VITE_APP_MODE: <NACHET_FRONTEND_VITE_APP_MODE>
