apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: librechat
  name: librechat-images-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
