apiVersion: apps/v1
kind: Deployment
metadata:
  name: librechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librechat
  template:
    metadata:
      labels:
        app: librechat
    spec:
      containers:
        - name: librechat
          image: ghcr.io/danny-avila/librechat:latest
          ports:
            - name: http
              containerPort: 3080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 5
            httpGet:
              path: /health
              port: 3080
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 3
            httpGet:
              path: /ready
              port: 3080
          resources:
            requests:
              cpu: "2000m"
              memory: "4Gi"
            limits:
              cpu: "2000m"
              memory: "6Gi"
          envFrom:
            - configMapRef:
                name: librechat-config
            - secretRef:
                name: librechat-secrets
          volumeMounts:
            - name: config-yaml
              mountPath: "/app/librechat.yaml"
              subPath: "librechat.yaml"
              readOnly: true
            - name: image-volume
              mountPath: "/app/client/public/images"
      volumes:
        - name: config-yaml
          configMap:
            name: librechat-config
        - name: image-volume
          persistentVolumeClaim:
            claimName: librechat-images-pvc
---
kind: Secret
apiVersion: v1
metadata:
  name: librechat-secrets
  annotations:
    avp.kubernetes.io/path: "kv/data/librechat/librechat-client"
    avp.kubernetes.io/secret-version: "5"
stringData:
  SEARCH: "true"
  MEILI_MASTER_KEY: <MEILI_MASTER_KEY>
  JWT_SECRET: <JWT_SECRET>
  JWT_REFRESH_SECRET: <JWT_REFRESH_SECRET>
