apiVersion: apps/v1
kind: Deployment
metadata:
  name: librechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librechat
  template:
    metadata:
      labels:
        app: librechat
    spec:
      initContainers:
        - name: take-data-dir-ownership
          image: alpine:3
          command: ["sh", "-c", "chown -R 1000:3000 /app/client/public/images"]
          volumeMounts:
            - name: image-volume
              mountPath: /app/client/public/images
      containers:
        - name: librechat
          image: ghcr.io/danny-avila/librechat:latest
          ports:
            - containerPort: 3080
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "2"
              memory: "6Gi"
          envFrom:
            - configMapRef:
                name: librechat-configenv
          volumeMounts:
            - name: config-yaml
              mountPath: "/app/librechat.yaml"
              subPath: "librechat.yaml"
              readOnly: true
            - name: image-volume
              mountPath: "/app/client/public/images"
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
          securityContext:
            runAsUser: 1000
            runAsGroup: 3000
      volumes:
        - name: config-yaml
          configMap:
            name: librechat-config
        - name: image-volume
          persistentVolumeClaim:
            claimName: librechat-images-pvc
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "librechat-spc"
---
apiVersion: v1
kind: Service
metadata:
  name: librechat
spec:
  clusterIP: None
  selector:
    app: librechat
  ports:
    - port: 3080
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: librechat
  name: librechat-images-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
