---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
spec:
  selector:
    matchLabels:
      app: meilisearch
  replicas: 1
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: chat-meilisearch
          image: getmeili/meilisearch:v1.7.3
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: meilisearch-secrets
          ports:
            - containerPort: 7700
          volumeMounts:
            - name: storage
              mountPath: /meili_data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: librechat-meilisearch-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librechat-meilisearch-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
spec:
  clusterIP: None
  selector:
    app: meilisearch
  ports:
    - port: 7700
      targetPort: 7700
---
kind: Secret
apiVersion: v1
metadata:
  name: meilisearch-secrets
  annotations:
    avp.kubernetes.io/path: "kv/data/librechat/meilisearch"
    avp.kubernetes.io/secret-version: "1"
stringData:
  SEARCH: "true"
  MEILI_MASTER_KEY: <MEILI_MASTER_KEY>
  MEILI_HOST: "http://0.0.0.0:7700"
  MEILI_NO_ANALYTICS: "true"
