---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
spec:
  selector:
    matchLabels:
      app: meilisearch
  replicas: 1
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: chat-meilisearch
          image: getmeili/meilisearch:v1.7.3
          imagePullPolicy: Always
          ports:
            - containerPort: 7700
          volumeMounts:
            - name: storage
              mountPath: /meili_data
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: librechat-meilisearch-pvc
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "librechat-spc"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librechat-meilisearch-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
spec:
  clusterIP: None
  selector:
    app: meilisearch
  ports:
    - port: 7700
      targetPort: 7700
