---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      initContainers:
        - name: take-data-dir-ownership
          image: alpine:3
          command: ["sh", "-c", "chown -R 1001:1001 /data/db"]
          volumeMounts:
            - name: storage
              mountPath: /data/db
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - agent
      containers:
        - name: mongodb
          image: mongo:6
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - >
              exec mongod --noauth --bind_ip_all
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              cpu: 100m
              memory: 4Gi
            limits:
              cpu: 500m
              memory: 6Gi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: librechat-mongodb-pvc
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librechat-mongodb-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
