apiVersion: apps/v1
kind: Deployment
metadata:
  name: vectordb
spec:
  selector:
    matchLabels:
      app: vectordb
  replicas: 1
  template:
    metadata:
      labels:
        app: vectordb
    spec:
      containers:
        - name: vectordb
          image: ankane/pgvector:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: librechat-vectordb-pvc
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "librechat-spc"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librechat-vectordb-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: vectordb
spec:
  type: ClusterIP
  selector:
    app: vectordb
  ports:
    - port: 5432
      name: http
