apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rag-api
  template:
    metadata:
      labels:
        app: rag-api
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - agent
      containers:
        - name: rag-api
          image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: rag-api-secrets
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
      volumes:
        - name: uploads
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: rag-api
spec:
  type: ClusterIP
  selector:
    app: rag-api
  ports:
    - port: 8000
      name: http
---
kind: Secret
apiVersion: v1
metadata:
  name: rag-api-secrets
stringData:
  DB_HOST: "vectordb"
  POSTGRES_DB: <path:kv/data/librechat/vectordb#POSTGRES_DB#2>
  POSTGRES_USER: <path:kv/data/librechat/vectordb#POSTGRES_USER#2>
  POSTGRES_PASSWORD: <path:kv/data/librechat/vectordb#POSTGRES_PASSWORD#2>
  DB_PORT: "5432"
  RAG_PORT: "8000"
  DEBUG_RAG_API: "true"
  EMBEDDINGS_PROVIDER: azure
  EMBEDDINGS_MODEL: <path:kv/data/librechat/rag-api#EMBEDDINGS_MODEL#1>
  RAG_AZURE_OPENAI_ENDPOINT: <path:kv/data/librechat/rag-api#RAG_AZURE_OPENAI_ENDPOINT#1>
  RAG_AZURE_OPENAI_API_VERSION: <path:kv/data/librechat/rag-api#RAG_AZURE_OPENAI_API_VERSION#1>
  RAG_AZURE_OPENAI_API_KEY: <path:kv/data/librechat/rag-api#RAG_AZURE_OPENAI_API_KEY#1>
  JWT_SECRET: <path:kv/data/librechat/librechat-client#JWT_SECRET#7>
