apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-api
  template:
    metadata:
      labels:
        app: rag-api
    spec:
      containers:
        - name: rag-api
          image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: rag-api-secrets
            - configMapRef:
                name: librechat-config
---
apiVersion: v1
kind: Service
metadata:
  name: rag-api
spec:
  type: ClusterIP
  selector:
    app: rag-api
  ports:
    - port: 8000
      name: http
---
kind: Secret
apiVersion: v1
metadata:
  name: rag-api-secrets
  annotations:
    avp.kubernetes.io/path: "kv/data/librechat/vectordb"
    avp.kubernetes.io/secret-version: "3"
stringData:
  DB_HOST: "vectordb"
  POSTGRES_DB: <POSTGRES_DB>
  POSTGRES_USER: <POSTGRES_USER>
  POSTGRES_PASSWORD: <POSTGRES_PASSWORD>
  DB_PORT: "5432"
  RAG_PORT: "8000"
  RAG_AZURE_OPENAI_ENDPOINT: <RAG_AZURE_OPENAI_ENDPOINT>
  RAG_AZURE_OPENAI_API_VERSION: <RAG_AZURE_OPENAI_API_VERSION>
  RAG_AZURE_OPENAI_API_KEY: <RAG_AZURE_OPENAI_API_KEY>
