apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
        - name: landing-page
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: landing-page-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: landing-page-content
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>VPN Reminder</title>
    </head>
    <body>
      <h1>Remember to Activate VPN</h1>
      <p>Please connect to your VPN before accessing this application.</p>
      <br>
      ---
      <h1>Veuillez activer le VPN</h1>
      <p>Veuillez vous connecter à votre VPN avant d'accéder à cette application.</p>

      <script>
        const params = new URLSearchParams(window.location.search);
        const redirectUrl = params.get('redirect');
        const isConnectedToVPN = true;

        if (isConnectedToVPN && redirectUrl) {
          window.location.href = redirectUrl;
        }
      </script>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: landing-page-svc
spec:
  selector:
    app: landing-page
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing-page-ingress
  annotations:
    external-dns.alpha.kubernetes.io/target: inspection.alpha.canada.ca
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - landing.inspection.alpha.canada.ca
      secretName: aciacfia-tls
  rules:
    - host: landing.inspection.alpha.canada.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing-page-svc
                port:
                  number: 80
