name: Update Secret Version
description: Template for updating the secret version and its content in a specific service/application.
title: "Update Secret Version for [Service/Application Name]"
labels: ["good first issue"]
projects: ["DevSecOps"]
body:
  - type: textarea
    id: issue_description
    attributes:
      label: "## Issue Description"
      description:
        "Please describe the reason for the secret update and the expected outcome.
        Include any relevant details or context necessary for understanding the change."
    validations:
      required: true
  - type: input
    id: related_issue
    attributes:
      label: Related issue
      description: "Link to related issue"
      placeholder: "e.g., https://github.com/ai-cfia/finesse-frontend/issues/95"
    validations:
      required: false
  - type: textarea
    id: checklist
    attributes:
      label: "Checklist"
      value:
        "- [ ] I have incremented the `avp.kubernetes.io/secret-version` annotation.\n
        - [ ] I updated the secret manifest with required keys if necessary.\n
        - [ ] I updated secrets values in Vault"
