---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-acia-cfia-staging-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  sources:
    - chart: istio
      helm:
        releaseName: istio
        valueFiles:
          - $values/kubernetes/aks/system/istio/acia-cfia-staging-cluster/helm/values.yaml
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.22.0-beta.0
    - repoURL: https://github.com/ai-cfia/howard.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
