---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argo-app.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: istiod
    path: patches/patch.yaml
