---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gh-runner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: gh-runner
    server: https://kubernetes.default.svc
  sources:
    - chart: actions-runner-controller
      helm:
        releaseName: actions-runner-controller
        valueFiles:
          - $values/kubernetes/aks/system/gh-runner/helm/values.yaml
      oci: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    - repoURL: https://github.com/ai-cfia/howard.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ai-cfia/howard.git
      path: kubernetes/aks/system/gh-runner/base
      targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
