---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ailab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd-image-updater.argoproj.io/image-list: ailab=ghcr.io/ai-cfia/ai-cfia-ia-acia.github.io:main
    argocd-image-updater.argoproj.io/ailab.update-strategy: digest
spec:
  project: default
  destination: # docker pull ghcr.io/ai-cfia/ai-cfia-ia-acia.github.io:8ccb687ed6dfd3193dd016c9cbf286f0fea9f415
    server: https://kubernetes.default.svc
    namespace: ailab
  source:
    repoURL: https://github.com/ai-cfia/howard.git
    path: kubernetes/aks/apps/ailab/prod
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
