apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vouch-proxy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: vouch-proxy
    server: https://kubernetes.default.svc
  sources:
    - chart: vouch
      repoURL: https://vouch.github.io/helm-charts
      targetRevision: 3.2.0
      plugin:
        env:
          - name: HELM_VALUES
            value: |
              config:
                vouch:
                  # only used for github orgs/teams. To be removed when we move to azure.
                  teamWhitelist:
                    - ai-cfia
                    # - ai-cfia/devops if we only want specific teams.
                  allowAllUsers: false
                  # domains - VOUCH_DOMAINS
                  # each of these domains must serve the url https://vouch.$domains[0] https://vouch.$domains[1] ...
                  # so that the cookie which stores the JWT can be set in the relevant domain
                  # you usually *don't* want to list every individual website that will be protected
                  # if you have siteA.internal.yourdomain.com and siteB.internal.yourdomain.com
                  # then your domains should be set as yourdomain.com or perhaps internal.yourdomain.com
                  # usually you'll just have one.
                  # Comment `domains:` out if you set allowAllUser:true
                  domains:
                  - inspection.alpha.canada.ca
                  cookie:
                    name: jxVouchCookie
                    domain: inspection.alpha.canada.ca
                    secure: true
                    httpOnly: true
                    maxAge: 14400
                    sameSite: none
                  jwt:
                    issuer: Vouch
                    maxAge: 240
                    compress: true
                  session:
                    name: jxVouchSession
                  headers:
                    jwt: X-Vouch-Token
                    querystring: access_token
                    accesstoken: X-Vouch-IdP-AccessToken
                    idtoken: X-Vouch-IdP-IdToken
                    claims:
                      - name
                      - email
                      - groups
                oauth:
                  # Azure
                  # scopes: [openid, email, profile]
                  # provider: azure
                  # client_id: <id>
                  # client_secret: <secret>
                  # auth_url: https://login.microsoftonline.com/<tenantID>/oauth2/v2.0/authorize
                  # token_url: https://login.microsoftonline.com/<tenantID>/oauth2/v2.0/token
                  # callback_url: https://vouch.inspection.alpha.canada.ca/auth
                  # azure_token: id_token

                  # GitHub // to be removed when we move to azure
                  # https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-authorization-options-for-oauth-apps/
                  # Done at https://github.com/settings/applications/new
                  provider: github
                  client_id: <ailab-key-vault-dev#vouch-github-client-id>
                  client_secret: <ailab-key-vault-dev#vouch-github-client-secret>
                  scopes:
                    - read:user
                    - user:email
                    - read:org
    - repoURL: https://github.com/ai-cfia/howard.git
      path: kubernetes/aks/system/vouch-proxy/base
      targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
