apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vouch-proxy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: vouch-proxy
    server: https://kubernetes.default.svc
  sources:
    - chart: vouch
      helm:
        releaseName: vouch
        valueFiles:
          - $values/kubernetes/aks/system/vouch-proxy/helm/values.yaml
      repoURL: https://vouch.github.io/helm-charts
      targetRevision: 3.2.0
    - repoURL: https://github.com/ai-cfia/howard.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ai-cfia/howard.git
      path: kubernetes/aks/system/vouch-proxy/base
      targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
