---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ori
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ori
  sources:
    - chart: kratos
      helm:
        releaseName: ori-kratos
        valueFiles:
          - $values/kubernetes/aks/system/ori/base/kratos/values.yaml
      repoURL: https://k8s.ory.sh/helm/charts
      targetRevision: 0.39.1
    - repoURL: https://github.com/ai-cfia/howard.git
      path: kubernetes/aks/system/ori/base
      targetRevision: HEAD
    - repoURL: https://github.com/ai-cfia/howard.git
      path: kubernetes/aks/system/ori/kratos
      targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
