kind: Secret
apiVersion: v1
metadata:
  name: jsantos-webtop-secrets
  annotations:
    avp.kubernetes.io/path: "kv/data/webtop/test"
    avp.kubernetes.io/secret-version: "1"
stringData:
  PUID: <PUID>
  PGID: <PGID>
  TZ: <TZ>
  TITLE: <TITLE>
  CUSTOM_USER: <CUSTOM_USER>
  PASSWORD: <PASSWORD>
