apiVersion: apps/v1
kind: Deployment
metadata:
  name: spevraire-webtop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spevraire-webtop
  template:
    metadata:
      labels:
        app: spevraire-webtop
    spec:
      containers:
      - name: webtop
        image: ghcr.io/ai-cfia/webtop-ubuntu-kde:main
        ports:
        - containerPort: 3000
        env:
        - name: DOCKER_HOST
          value: "tcp://localhost:2375"
        - name: DOCKER_TLS_CERTDIR
          value: ""
        envFrom:
        - secretRef:
            name: spevraire-webtop-secrets
        volumeMounts:
        - name: config
          mountPath: /config
      - name: docker-dind
        image: docker:dind
        securityContext:
          privileged: true
        ports:
        - containerPort: 2375
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        args:
        - "--host=tcp://0.0.0.0:2375"
        - "--tls=false"
        volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: spevraire-webtop-config-pvc
      - name: docker-graph-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: spevraire-webtop-service
spec:
  type: ClusterIP
  selector:
    app: spevraire-webtop
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spevraire-webtop-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
