---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vikunja
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: vikunja
    server: https://kubernetes.default.svc
  sources:
    - chart: vikunja
      helm:
        releaseName: vikunja
        valueFiles:
          - $values/kubernetes/aks/apps/vikunja/helm/values.yaml
      repoURL: kolaente.dev/vikunja/vikunja
      targetRevision: 0.4.3
    - repoURL: https://github.com/ai-cfia/howard.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
