apiVersion: v1
kind: Secret
metadata:
  name: minio_secret
  annotations:
    avp.kubernetes.io/path: "kv/data/devsecops_admin_keys"
    avp.kubernetes.io/secret-version: "13"
stringData:
  rootPassword: <rootPassword>
  rootUser: <rootUser>
type: Opaque
