apiVersion: apps/v1
kind: Deployment
metadata:
  name: oneuptime-custom-probe-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oneuptime-custom-probe-0
  template:
    metadata:
      labels:
        app: oneuptime-custom-probe-0
    spec:
      containers:
        - name: oneuptime-probe
          image: ghcr.io/oneuptime/probe:7.0.1978
          env:
            - name: PROBE_KEY
              valueFrom:
                secretKeyRef:
                  name: oneuptime-probe-secrets
                  key: PROBE_KEY
            - name: PROBE_ID
              valueFrom:
                secretKeyRef:
                  name: oneuptime-probe-secrets
                  key: PROBE_ID
            - name: ONEUPTIME_URL
              value: "https://oneuptime.inspection.alpha.canada.ca"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
      hostNetwork: true
---
apiVersion: v1
kind: Secret
metadata:
  name: oneuptime-probe-secrets
  annotations:
    avp.kubernetes.io/path: "kv/data/system/oneuptime/probe-0"
    avp.kubernetes.io/secret-version: "2"
stringData:
  PROBE_KEY: <PROBE_KEY>
  PROBE_ID: <PROBE_ID>
