---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-acia-cfia-gpu-staging-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://acia-cfia-gpu-staging-dns-wazsxt3w.hcp.canadacentral.azmk8s.io:443
    namespace: istio-system
  sources:
    - chart: istiod
      helm:
        releaseName: istiod
        valueFiles:
          - $values/kubernetes/aks/system/istio/acia-cfia-gpu-staging-cluster/helm/values.yaml
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.22.0-beta.0
    - repoURL: https://github.com/ai-cfia/howard.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/ai-cfia/howard.git
      path: kubernetes/aks/system/istio/acia-cfia-gpu-staging-cluster/base
      targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        topology.istio.io/controlPlaneClusters: acia-cfia-staging-cluster
        istio-system topology.istio.io/network: network2
