---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finesse-backend
  namespace: finesse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finesse-backend
  template:
    metadata:
      labels:
        app: finesse-backend
    spec:
      containers:
        - name: finesse-backend
          image: ghcr.io/ai-cfia/finesse-backend:main
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: finesse-secrets
          env:
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: finesse-backend-svc
  namespace: finesse
spec:
  clusterIP: None
  selector:
    app: finesse-backend
  ports:
    - protocol: TCP
      port: 8080
