---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ori-postgresql
  namespace: ori
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:15.4

  superuserSecret:
    name: superuser-secret

  bootstrap:
    initdb:
      database: kratos
      owner: kratos
      secret:
        name: kratos-db-secret

  storage:
    size: 1Gi
