apiVersion: apps/v1
kind: Deployment
metadata:
  name: fertiscan-frontend-preview
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: fertiscan-frontend-preview
  template:
    metadata:
      labels:
        app: fertiscan-frontend-preview
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - fertiscan-frontend-preview
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.azure.com/role
                    operator: In
                    values:
                      - agent
      containers:
        - name: fertiscan-frontend-preview
          image: ghcr.io/ai-cfia/fertiscan-frontend:main
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: fertiscan-frontend-preview-secrets
          env:
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
            - name: NEXT_PUBLIC_DEBUG
              value: "true"
            - name: NEXT_PUBLIC_REPORT_ISSUE_URL
              value: "https://forms.office.com/Pages/ResponsePage.aspx?id=7aW1GIYd00GUoLwn2uMqsn9SKTgKSYtCg4t0B9x4uyJURE5HSkFCTkZHUEQyWkxJVElMODdFQ09HUCQlQCN0PWcu&r5a19e9d47d9f4ac497fb974c192da4b3=%22Fertiscan%22"
            - name: BACKEND_URL
              value: "https://fertiscan-preview.inspection.alpha.canada.ca/api"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          # resources:
          #   requests:
          #     cpu: "250m"
          #     memory: "512Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "1Gi"

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fertiscan-frontend-preview-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: fertiscan-frontend-preview

---
apiVersion: v1
kind: Service
metadata:
  name: fertiscan-frontend-preview-svc
spec:
  clusterIP: None
  selector:
    app: fertiscan-frontend-preview
  ports:
    - protocol: TCP
      port: 3000
