---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: fertiscan-preview-pgsql-cluster
spec:
  description: "Fertiscan preview PostgreSQL cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:15.8
  instances: 3
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: fertiscan
      owner: app
      secret:
        name: fertiscan-preview-pgsql-app-user

  superuserSecret:
    name: fertiscan-preview-pgsql-superuser

  storage:
    size: 20Gi

  # TODO: Configure backup
  # backup:
  #   barmanObjectStore:
  #     destinationPath: "<destination path here>"
  #     azureCredentials:
  #       connectionString:
  #         name: azure-creds
  #         key: AZURE_CONNECTION_STRING
  #       storageAccount:
  #         name: azure-creds
  #         key: AZURE_STORAGE_ACCOUNT
  #       storageKey:
  #         name: azure-creds
  #         key: AZURE_STORAGE_KEY
  #       storageSasToken:
  #         name: azure-creds
  #         key: AZURE_STORAGE_SAS_TOKEN
  #   retentionPolicy: "30d"
