---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finesse-frontend
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: finesse-frontend-internal
  template:
    metadata:
      labels:
        app: finesse-frontend-internal
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - finesse-frontend-internal
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - agent
      containers:
        - name: finesse-frontend
          image: ghcr.io/ai-cfia/finesse-frontend:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests:
              cpu: 200m
              memory: 750Mi
            limits:
              cpu: 400m
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: finesse-frontend-svc
spec:
  clusterIP: None
  selector:
    app: finesse-frontend-internal
  ports:
    - protocol: TCP
      port: 3000
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: finesse-frontend-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: finesse-frontend
