apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: finesse-internal-spc
spec:
  provider: azure
  secretObjects:
    - secretName: finesse-internal-secrets
      type: Opaque
      labels:
        app: finesse-backend
      data:
        - objectName: azure-openai-chatgpt-deployment
          key: AZURE_OPENAI_CHATGPT_DEPLOYMENT
        - objectName: azure-openai-gpt-deployment
          key: AZURE_OPENAI_GPT_DEPLOYMENT
        - objectName: finesse-backend-azure-search-api-key
          key: FINESSE_BACKEND_AZURE_SEARCH_API_KEY
        - objectName: finesse-backend-azure-search-endpoint
          key: FINESSE_BACKEND_AZURE_SEARCH_ENDPOINT
        - objectName: finesse-backend-azure-search-index-name
          key: FINESSE_BACKEND_AZURE_SEARCH_INDEX_NAME
        - objectName: louis-dsn
          key: LOUIS_DSN
        - objectName: louis-schema
          key: LOUIS_SCHEMA
        - objectName: openai-api-engine
          key: OPENAI_API_ENGINE
        - objectName: openai-api-key
          key: OPENAI_API_KEY
        - objectName: openai-api-version
          key: OPENAI_API_VERSION
        - objectName: openai-endpoint
          key: OPENAI_ENDPOINT
        - objectName: finesse-backend-azure-search-params
          key: FINESSE_BACKEND_AZURE_SEARCH_PARAMS
        - objectName: finesse-backend-azure-search-transform-map
          key: FINESSE_BACKEND_AZURE_SEARCH_TRANSFORM_MAP
        - objectName: finesse-backend-llamaindex-embed-model-params
          key: FINESSE_BACKEND_LLAMAINDEX_EMBED_MODEL_PARAMS
        - objectName: finesse-backend-llamaindex-vector-store-params
          key: FINESSE_BACKEND_LLAMAINDEX_VECTOR_STORE_PARAMS
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: fa9cd720-ddc4-4dc8-9be6-5d0fc8c4a3fb  # to be updated with identity from dev cluster. current one is from staging azurekeyvaultsecretprovider-acia-cfia-staging-cluster
    keyvaultName: ailab-key-vault-dev
    cloudName: ""
    objects: |
      array:
        - |
          objectName: azure-openai-chatgpt-deployment
          objectType: secret
          objectVersion: ""
        - |
          objectName: azure-openai-gpt-deployment
          objectType: secret
          objectVersion: ""
        - |
          objectName: finesse-backend-azure-search-api-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: finesse-backend-azure-search-endpoint
          objectType: secret
          objectVersion: ""
        - |
          objectName: finesse-backend-azure-search-index-name
          objectType: secret
          objectVersion: ""
        - |
          objectName: louis-dsn
          objectType: secret
          objectVersion: ""
        - |
          objectName: louis-schema
          objectType: secret
          objectVersion: ""
        - |
          objectName: openai-api-engine
          objectType: secret
          objectVersion: ""
        - |
          objectName: openai-api-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: openai-api-version
          objectType: secret
          objectVersion: ""
        - |
          objectName: openai-endpoint
          objectType: secret
          objectVersion: ""
        - |
          objectName: finesse-backend-azure-search-params
          objectType: secret
          objectVersion: ""
        - |
          objectName: finesse-backend-azure-search-transform-map
          objectType: secret
          objectVersion: ""
        - |
          objectName: finesse-backend-llamaindex-embed-model-params
          objectType: secret
          objectVersion: ""
        - |
          objectName: finesse-backend-llamaindex-vector-store-params
          objectType: secret
          objectVersion: ""
    tenantId: 18b5a5ed-1d86-41d3-94a0-bc27dae32ab2
