apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oneuptime-custom-probe
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: oneuptime
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/ai-cfia/howard.git
      path: kubernetes/aks/system/oneuptime/custom-probe/base
      targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
