---
kind: Secret
apiVersion: v1
metadata:
  name: superuser-secret
  namespace: postgresml
  annotations:
    avp.kubernetes.io/path: "kv/postgresml/pgsql-ml-01/database"
    avp.kubernetes.io/secret-version: "1"
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <password>
---
kind: Secret
apiVersion: v1
metadata:
  name: superuser-secret
  namespace: postgresml
  annotations:
    avp.kubernetes.io/path: "kv/postgresml/pgsql-ml-01/superuser"
    avp.kubernetes.io/secret-version: "1"
type: kubernetes.io/basic-auth
stringData:
  password: <password>
