apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.27.0
      helm:
        releaseName: vault
        valueFiles:
          - $values/kubernetes/aks/system/vault/helm/values.yaml
    - repoURL: https://github.com/ai-cfia/howard.git 
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
    project: default

