apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: docker-io-helm-oci
  namespace: argocd
stringData:
  url: ghcr.io/actions/actions-runner-controller-charts
  name: actions-runner-controller-charts
  type: helm
  enableOCI: "true"
