# Commented so that its not applied by argocd. This is a secret that is used by the argocd-vault-plugin. It will be manually created in the argocd namespace.
# apiVersion: v1
# kind: Secret
# metadata:
#   name: vault-configuration
#   namespace: argocd
# data:
#   VAULT_ADDR: aHR0cHM6Ly92YXVsdC52YXVsdDo4MjAw
#   AVP_GITHUB_TOKEN: <>
#   AVP_TYPE: dmF1bHQ=
#   AVP_AUTH_TYPE: Z2l0aHVi
#   VAULT_CACERT: L3ZhdWx0L3Rscy92YXVsdC5jYQ==
#   VAULT_CAPATH: L3ZhdWx0L3Rscy92YXVsdC5jYQ==
#   VAULT_CLIENT_CERT: L3ZhdWx0L3Rscy92YXVsdC5jcnQ=
#   VAULT_CLIENT_KEY: L3ZhdWx0L3Rscy92YXVsdC5rZXk=
# type: Opaque
