apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-alerting-rules
  labels:
    release: monitoring-metrics
data:
  rules.yaml: |
    groups:
      - name: test_alert
        rules:
          - alert: TestAlert
            expr: sum(rate({app="loki"} | logfmt | level="info"[1m])) by (container) > 0
            for: 1m
            labels:
                severity: warning
            annotations:
                summary: Loki info warning per minute rate > 0
                message: 'Loki warning per minute rate > 0 container:"{{`{{`}} $labels.container {{`}}`}}"'
      # - name: test_app_critical
      #   rules:
      #     - alert: CriticalLogDetected
      #       expr: count_over_time({application="test-app", severity="critical"}[1m]) > 0
      #       for: 1m
      #       labels:
      #         severity: critical
      #       annotations:
      #         summary: "Critical log found in test-app"
      #         description: "Log entry with severity `critical` detected in test-app."
