apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: istio-tls
  namespace: istio-system
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "458b22f7-31a4-40c8-be76-ee7a3096f199"
    keyvaultName: staging-vault-6biac
    objects: |
      array:
        - |
          objectName: acia-cfia-gpu-staging-cluster-ca-cert
          objectAlias: ca-key.pem # The secret contains both the certificate and private key
          objectType: secret
        - |
          objectName: acia-cfia-gpu-staging-cluster-ca-cert
          objectAlias: ca-cert.pem
          objectType: cert
        - |
          objectName: root-cert
          objectAlias: root-cert.pem
          objectType: secret
        - |
          objectName: acia-cfia-gpu-staging-cluster-cert-chain
          objectAlias: cert-chain.pem
          objectType: secret
    tenantId: "18b5a5ed-1d86-41d3-94a0-bc27dae32ab2"
