schedules:
- cron: '0 0 * * Mon-Fri'
  displayName: Stop cluster on weekdays at 20 PM (EST)
  branches:
    include:
    - main
  always: true

- cron: '0 12 * * Mon-Fri'
  displayName: Start cluster on weekdays at 8 AM (EST)
  branches:
    include:
    - main
  always: true

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: cron-toggle-power-k8s-cluster

stages:
- stage: ManageCluster
  jobs:
  - job: ManageAKSCluster
    steps:
    - task: AzureCLI@2
      displayName: "Login to Azure"
      inputs:
        azureSubscription: $(serviceConnectionName)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Successfully logged in to Azure"

    - task: AzureCLI@2
      displayName: "Toggle power (on/off) k8s cluster"
      inputs:
        azureSubscription: $(serviceConnectionName)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          # Conditional operation based on the time trigger
          if [ "$(Build.CronSchedule.DisplayName)" == "Stop cluster on weekdays at 20 PM (EST)" ]; then
            echo "Stopping AKS cluster based on schedule..."
            az aks stop --name $(aksName) --resource-group $(resourceGroupName)
            az aks show --name $(aksName) --resource-group $(resourceGroupName)
          elif [ "$(Build.CronSchedule.DisplayName)" == "Start cluster on weekdays at 8 AM (EST)" ]; then
            echo "Starting AKS cluster based on schedule..."
            az aks start --name $(aksName) --resource-group $(resourceGroupName)
            az aks show --name $(aksName) --resource-group $(resourceGroupName)
          fi
