---
name: Infra integration workflow

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize

jobs:

  markdown-check:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-markdown-check.yml@76-as-a-devops-i-would-like-to-fix-the-markdown-lint-workflow

  yaml-check:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-yaml-check.yml@main

  repo-standard:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-repo-standards-validation.yml@main
    secrets: inherit

  terraform-lint:
    name: Terraform Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Terraform Initialization
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check
