name: Python api-test workflows

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize

jobs:
  lint-test:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-lint-test-python.yml@main
    secrets: inherit

  markdown-check:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-markdown-check.yml@main
    with:
      config-file-path: '.mlc_config.json'
    secrets: inherit

  repo-standard:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-repo-standards-validation.yml@main
    secrets: inherit
