---
name: Howard integration workflow

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize

jobs:
  markdown-check:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-markdown-check.yml@main

  yaml-check:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-yaml-check.yml@main
    with:
      config-file-path: '.yamllint.yml'

  repo-standard:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-repo-standards-validation.yml@main
    secrets: inherit

  terraform-check:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-terraform-check.yml@main
    with:
      config-file-path: '.tflint.hcl'

  ansible-lint:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-lint-ansible.yml@116-create-a-github-workflow-to-lint-any-ansible-playbooks
    with:
      ansible-lint-config: '.ansible-lint'
