name: Ai-cfia repo standard and markdown check

on: 
  pull_request:
    types:
      - opened
      - closed
      - synchronize

jobs:
  repo-standard:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-repo-standards-validation.yml@71-fix-every-workflow-inside-this-repository-and-make-sure-nachet-finesse-and-infra-have-the-right-workflow
    secrets: inherit

  markdown-check:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-markdown-check.yml@main
    with:
      config-file-path: '.mlc_config.json'