---
name: Howard integration workflow

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize
  push:

jobs:
  markdown-check:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-markdown-check.yml@main

  yaml-check:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-yaml-check.yml@main
    with:
      config-file-path: '.yamllint.yml'

  repo-standard:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-repo-standards-validation.yml@main
    secrets: inherit

  terraform-check:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-terraform-check.yml@main
    with:
      config-file-path: '.tflint.hcl'

  pr-labelling:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-pr-labelling.yml@main
    secrets: inherit

  mkdocs-gh-pages-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: pip install pymdown-extensions
      - run: mkdocs build -f mkdocs-en.yml
      - run: mkdocs build -f mkdocs-fr.yml
      - run: cp index.html site/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site

  # Missing configuration permissions for ours VM's so this won't be applied for now
  # ansible-lint-and-apply:
  #   uses:
  #     ai-cfia/github-workflows/.github/workflows/workflow-lint-and-apply-ansible.yml@116-create-a-github-workflow-to-lint-any-ansible-playbooks
  #   with:
  #     ansible-lint-config: '.ansible-lint'
  #     ansible-variable-file: 'ansible/variables.yml'
  #     ansible-inventory-file: 'ansible/inventory'
  #     ansible-playbook-file: 'ansible/playbook.yml'
  #   secrets: inherit
